spring.application.name=My Blog
spring.profiles.active=test

spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Le secret doit contenir au moins 32 caracteres
security.jwt.secret-key=${JWT_SECRET_KEY}

# 1h in millisecond
security.jwt.expiration-time=${JWT_EXPIRATION}

cors.allowed-origin=${CORS_ALLOWED_ORIGIN}