spring.datasource.url=jdbc:h2:mem:wild_blog_test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

JWT_SECRET_KEY=9uXtwQBv7gymBpmJaqVoiLX8kzhrY5VeSASAXZXAZSASASAS
JWT_EXPIRATION=360000
CORS_ALLOWED_ORIGIN=http://localhost:4200